services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: cocktails_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  cocktail-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cocktails_db
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - MODEL_NAME=all-MiniLM-L6-v2
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

volumes:
  postgres_data:
